/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPlacesSearchRouteImport } from './routes/api/places/search'
import { Route as ApiPlacesPhotoUriRouteImport } from './routes/api/places/photo-uri'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesSearchRoute = ApiPlacesSearchRouteImport.update({
  id: '/api/places/search',
  path: '/api/places/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesPhotoUriRoute = ApiPlacesPhotoUriRouteImport.update({
  id: '/api/places/photo-uri',
  path: '/api/places/photo-uri',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/places/photo-uri': typeof ApiPlacesPhotoUriRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/places/photo-uri': typeof ApiPlacesPhotoUriRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/api/places/photo-uri': typeof ApiPlacesPhotoUriRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/api/places/photo-uri' | '/api/places/search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/api/places/photo-uri' | '/api/places/search'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/api/places/photo-uri'
    | '/api/places/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApiPlacesPhotoUriRoute: typeof ApiPlacesPhotoUriRoute
  ApiPlacesSearchRoute: typeof ApiPlacesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/search': {
      id: '/api/places/search'
      path: '/api/places/search'
      fullPath: '/api/places/search'
      preLoaderRoute: typeof ApiPlacesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/photo-uri': {
      id: '/api/places/photo-uri'
      path: '/api/places/photo-uri'
      fullPath: '/api/places/photo-uri'
      preLoaderRoute: typeof ApiPlacesPhotoUriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApiPlacesPhotoUriRoute: ApiPlacesPhotoUriRoute,
  ApiPlacesSearchRoute: ApiPlacesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
